name: MiniApp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 10AM & 10PM UTC
    - cron:  '0 10,22 * * *'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y libjavascriptcoregtk-4.0-dev
      - run: pkg-config --libs javascriptcoregtk-4.0
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Test (Debug)
        run: swift test --configuration debug
      #- name: Test (Release)
        #run: swift test --configuration release -Xswiftc -enable-testing

  ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Test (Debug)
        run: xcodebuild clean test -configuration Debug -scheme "MiniApp-Package" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 14 Pro" 
      #- name: Test (Release)
        #run: xcodebuild clean test -configuration Release -scheme "MiniApp-Package" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 14 Pro" 

  tvos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Test (Debug)
        run: xcodebuild clean test -configuration Debug -scheme "MiniApp-Package" -sdk "appletvsimulator" -destination "platform=tvOS Simulator,name=Apple TV" 
      #- name: Test (Release)
        #run: xcodebuild clean test -configuration Release -scheme "MiniApp-Package" -sdk "appletvsimulator" -destination "platform=tvOS Simulator,name=Apple TV" 

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Test (Debug)
        run: swift test --configuration debug
      #- name: Test (Release)
        #run: swift test --configuration release -Xswiftc -enable-testing

  api-doc:
    runs-on: macos-12 # needed to be able to document SwiftUI
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Build documentation
        run: |
          swift -version
          export SWIFTPM_ENABLE_COMMAND_PLUGINS=1
          export DOCC_JSON_PRETTYPRINT="YES"

          # insert the docc dependency
          sed -I "" 's;^    dependencies: \[;    dependencies: [ .package(name: "swift-docc-plugin", url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0"), ;1' Package.swift

          swift package --allow-writing-to-directory docs \
            generate-documentation --target MiniApp \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path MiniApp \
            --output-path docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '.'


